// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using regrando.API.Data;

#nullable disable

namespace regrando.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240618230511_AnotherCreate")]
    partial class AnotherCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("regrando.API.Models.Aguas", b =>
                {
                    b.Property<int>("IdAgua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgua"));

                    b.Property<TimeSpan?>("HrAgua")
                        .HasColumnType("time");

                    b.Property<int?>("QtdAgua")
                        .HasColumnType("int");

                    b.HasKey("IdAgua");

                    b.ToTable("TB_AGUAS");

                    b.HasData(
                        new
                        {
                            IdAgua = 1,
                            HrAgua = new TimeSpan(0, 8, 0, 0, 0),
                            QtdAgua = 200
                        },
                        new
                        {
                            IdAgua = 2,
                            HrAgua = new TimeSpan(0, 12, 0, 0, 0),
                            QtdAgua = 300
                        });
                });

            modelBuilder.Entity("regrando.API.Models.Alimento", b =>
                {
                    b.Property<int>("IdAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlimento"));

                    b.Property<double>("Calorias")
                        .HasColumnType("float");

                    b.Property<double>("Carboidratos")
                        .HasColumnType("float");

                    b.Property<double>("Fibras")
                        .HasColumnType("float");

                    b.Property<double>("Gorduras")
                        .HasColumnType("float");

                    b.Property<string>("NomeAlimento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<double>("Proteinas")
                        .HasColumnType("float");

                    b.Property<double>("Sodio")
                        .HasColumnType("float");

                    b.HasKey("IdAlimento");

                    b.ToTable("TB_ALIMENTO");

                    b.HasData(
                        new
                        {
                            IdAlimento = 1,
                            Calorias = 124.0,
                            Carboidratos = 25.800000000000001,
                            Fibras = 0.40000000000000002,
                            Gorduras = 0.29999999999999999,
                            NomeAlimento = "Arroz branco cozido",
                            Proteinas = 2.6000000000000001,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 2,
                            Calorias = 77.0,
                            Carboidratos = 14.5,
                            Fibras = 6.4000000000000004,
                            Gorduras = 0.5,
                            NomeAlimento = "Feijão preto cozido",
                            Proteinas = 5.5,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 3,
                            Calorias = 143.0,
                            Carboidratos = 0.0,
                            Fibras = 0.0,
                            Gorduras = 1.2,
                            NomeAlimento = "Carne de frango grelhada",
                            Proteinas = 31.0,
                            Sodio = 70.0
                        },
                        new
                        {
                            IdAlimento = 4,
                            Calorias = 250.0,
                            Carboidratos = 0.0,
                            Fibras = 0.0,
                            Gorduras = 7.7000000000000002,
                            NomeAlimento = "Carne bovina magra grelhada",
                            Proteinas = 36.0,
                            Sodio = 60.0
                        },
                        new
                        {
                            IdAlimento = 5,
                            Calorias = 100.0,
                            Carboidratos = 1.0,
                            Fibras = 0.0,
                            Gorduras = 1.0,
                            NomeAlimento = "Peito de peru defumado",
                            Proteinas = 21.0,
                            Sodio = 830.0
                        },
                        new
                        {
                            IdAlimento = 6,
                            Calorias = 70.0,
                            Carboidratos = 0.59999999999999998,
                            Fibras = 0.0,
                            Gorduras = 5.0,
                            NomeAlimento = "Ovo cozido",
                            Proteinas = 6.5,
                            Sodio = 70.0
                        },
                        new
                        {
                            IdAlimento = 7,
                            Calorias = 66.0,
                            Carboidratos = 4.7000000000000002,
                            Fibras = 0.0,
                            Gorduras = 3.6000000000000001,
                            NomeAlimento = "Leite integral",
                            Proteinas = 3.2999999999999998,
                            Sodio = 42.0
                        },
                        new
                        {
                            IdAlimento = 8,
                            Calorias = 333.0,
                            Carboidratos = 0.69999999999999996,
                            Fibras = 0.0,
                            Gorduras = 25.100000000000001,
                            NomeAlimento = "Queijo prato",
                            Proteinas = 24.600000000000001,
                            Sodio = 618.0
                        },
                        new
                        {
                            IdAlimento = 9,
                            Calorias = 265.0,
                            Carboidratos = 48.0,
                            Fibras = 2.3999999999999999,
                            Gorduras = 3.3999999999999999,
                            NomeAlimento = "Pão francês",
                            Proteinas = 8.5999999999999996,
                            Sodio = 457.0
                        },
                        new
                        {
                            IdAlimento = 10,
                            Calorias = 717.0,
                            Carboidratos = 0.0,
                            Fibras = 0.0,
                            Gorduras = 81.099999999999994,
                            NomeAlimento = "Manteiga",
                            Proteinas = 0.5,
                            Sodio = 2.0
                        },
                        new
                        {
                            IdAlimento = 11,
                            Calorias = 828.0,
                            Carboidratos = 0.0,
                            Fibras = 0.0,
                            Gorduras = 91.599999999999994,
                            NomeAlimento = "Azeite de oliva",
                            Proteinas = 0.0,
                            Sodio = 2.0
                        },
                        new
                        {
                            IdAlimento = 12,
                            Calorias = 82.0,
                            Carboidratos = 18.5,
                            Fibras = 1.8,
                            Gorduras = 0.10000000000000001,
                            NomeAlimento = "Batata inglesa cozida",
                            Proteinas = 2.0,
                            Sodio = 2.0
                        },
                        new
                        {
                            IdAlimento = 13,
                            Calorias = 18.0,
                            Carboidratos = 3.8999999999999999,
                            Fibras = 1.2,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Tomate",
                            Proteinas = 0.90000000000000002,
                            Sodio = 5.0
                        },
                        new
                        {
                            IdAlimento = 14,
                            Calorias = 15.0,
                            Carboidratos = 2.8999999999999999,
                            Fibras = 1.3,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Alface",
                            Proteinas = 1.1000000000000001,
                            Sodio = 11.0
                        },
                        new
                        {
                            IdAlimento = 15,
                            Calorias = 35.0,
                            Carboidratos = 8.1999999999999993,
                            Fibras = 2.7999999999999998,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Cenoura crua",
                            Proteinas = 0.80000000000000004,
                            Sodio = 69.0
                        },
                        new
                        {
                            IdAlimento = 16,
                            Calorias = 105.0,
                            Carboidratos = 27.0,
                            Fibras = 3.1000000000000001,
                            Gorduras = 0.29999999999999999,
                            NomeAlimento = "Banana",
                            Proteinas = 1.3,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 17,
                            Calorias = 52.0,
                            Carboidratos = 14.0,
                            Fibras = 2.3999999999999999,
                            Gorduras = 0.5,
                            NomeAlimento = "Maçã",
                            Proteinas = 0.29999999999999999,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 18,
                            Calorias = 47.0,
                            Carboidratos = 12.0,
                            Fibras = 2.3999999999999999,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Laranja",
                            Proteinas = 1.2,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 19,
                            Calorias = 43.0,
                            Carboidratos = 11.0,
                            Fibras = 1.7,
                            Gorduras = 0.10000000000000001,
                            NomeAlimento = "Mamão",
                            Proteinas = 0.5,
                            Sodio = 8.0
                        },
                        new
                        {
                            IdAlimento = 20,
                            Calorias = 52.0,
                            Carboidratos = 13.1,
                            Fibras = 1.3999999999999999,
                            Gorduras = 0.10000000000000001,
                            NomeAlimento = "Abacaxi",
                            Proteinas = 0.5,
                            Sodio = 2.0
                        },
                        new
                        {
                            IdAlimento = 21,
                            Calorias = 30.0,
                            Carboidratos = 7.5999999999999996,
                            Fibras = 0.40000000000000002,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Melancia",
                            Proteinas = 0.59999999999999998,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 22,
                            Calorias = 19.0,
                            Carboidratos = 3.7000000000000002,
                            Fibras = 1.1000000000000001,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Água de coco",
                            Proteinas = 0.69999999999999996,
                            Sodio = 23.0
                        },
                        new
                        {
                            IdAlimento = 23,
                            Calorias = 39.0,
                            Carboidratos = 8.1999999999999993,
                            Fibras = 0.5,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Suco de laranja natural",
                            Proteinas = 0.59999999999999998,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 24,
                            Calorias = 2.0,
                            Carboidratos = 0.0,
                            Fibras = 0.0,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Café preto sem açúcar",
                            Proteinas = 0.5,
                            Sodio = 2.0
                        },
                        new
                        {
                            IdAlimento = 25,
                            Calorias = 1.0,
                            Carboidratos = 0.0,
                            Fibras = 0.0,
                            Gorduras = 0.0,
                            NomeAlimento = "Chá verde sem açúcar",
                            Proteinas = 0.0,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 26,
                            Calorias = 48.0,
                            Carboidratos = 3.6000000000000001,
                            Fibras = 0.0,
                            Gorduras = 0.10000000000000001,
                            NomeAlimento = "Iogurte natural desnatado",
                            Proteinas = 4.4000000000000004,
                            Sodio = 39.0
                        },
                        new
                        {
                            IdAlimento = 27,
                            Calorias = 290.0,
                            Carboidratos = 1.5,
                            Fibras = 0.0,
                            Gorduras = 20.800000000000001,
                            NomeAlimento = "Queijo minas frescal",
                            Proteinas = 13.4,
                            Sodio = 594.0
                        },
                        new
                        {
                            IdAlimento = 28,
                            Calorias = 165.0,
                            Carboidratos = 0.0,
                            Fibras = 0.0,
                            Gorduras = 3.6000000000000001,
                            NomeAlimento = "Peito de frango cozido",
                            Proteinas = 31.0,
                            Sodio = 74.0
                        },
                        new
                        {
                            IdAlimento = 29,
                            Calorias = 127.0,
                            Carboidratos = 19.199999999999999,
                            Fibras = 6.5999999999999996,
                            Gorduras = 0.69999999999999996,
                            NomeAlimento = "Feijão carioca cozido",
                            Proteinas = 8.4000000000000004,
                            Sodio = 6.0
                        },
                        new
                        {
                            IdAlimento = 30,
                            Calorias = 23.0,
                            Carboidratos = 3.6000000000000001,
                            Fibras = 2.2000000000000002,
                            Gorduras = 0.40000000000000002,
                            NomeAlimento = "Espinafre cozido",
                            Proteinas = 2.8999999999999999,
                            Sodio = 24.0
                        },
                        new
                        {
                            IdAlimento = 31,
                            Calorias = 17.0,
                            Carboidratos = 3.6000000000000001,
                            Fibras = 1.3,
                            Gorduras = 0.29999999999999999,
                            NomeAlimento = "Abobrinha cozida",
                            Proteinas = 1.2,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 32,
                            Calorias = 25.0,
                            Carboidratos = 5.9000000000000004,
                            Fibras = 3.0,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Berinjela cozida",
                            Proteinas = 1.0,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 33,
                            Calorias = 26.0,
                            Carboidratos = 6.2000000000000002,
                            Fibras = 1.0,
                            Gorduras = 0.10000000000000001,
                            NomeAlimento = "Abóbora cozida",
                            Proteinas = 1.0,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 34,
                            Calorias = 34.0,
                            Carboidratos = 6.5999999999999996,
                            Fibras = 2.6000000000000001,
                            Gorduras = 0.59999999999999998,
                            NomeAlimento = "Brócolis cozido",
                            Proteinas = 2.7999999999999998,
                            Sodio = 33.0
                        },
                        new
                        {
                            IdAlimento = 35,
                            Calorias = 16.0,
                            Carboidratos = 3.6000000000000001,
                            Fibras = 0.5,
                            Gorduras = 0.10000000000000001,
                            NomeAlimento = "Pepino",
                            Proteinas = 0.69999999999999996,
                            Sodio = 2.0
                        },
                        new
                        {
                            IdAlimento = 36,
                            Calorias = 25.0,
                            Carboidratos = 4.9000000000000004,
                            Fibras = 2.0,
                            Gorduras = 0.29999999999999999,
                            NomeAlimento = "Couve-flor cozida",
                            Proteinas = 1.8999999999999999,
                            Sodio = 30.0
                        },
                        new
                        {
                            IdAlimento = 37,
                            Calorias = 680.0,
                            Carboidratos = 3.2999999999999998,
                            Fibras = 0.0,
                            Gorduras = 77.599999999999994,
                            NomeAlimento = "Maionese",
                            Proteinas = 0.5,
                            Sodio = 620.0
                        },
                        new
                        {
                            IdAlimento = 38,
                            Calorias = 25.0,
                            Carboidratos = 6.0999999999999996,
                            Fibras = 2.5,
                            Gorduras = 0.10000000000000001,
                            NomeAlimento = "Repolho cru",
                            Proteinas = 1.3,
                            Sodio = 18.0
                        },
                        new
                        {
                            IdAlimento = 39,
                            Calorias = 41.0,
                            Carboidratos = 6.9000000000000004,
                            Fibras = 2.7999999999999998,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Cenoura cozida",
                            Proteinas = 0.90000000000000002,
                            Sodio = 69.0
                        },
                        new
                        {
                            IdAlimento = 40,
                            Calorias = 259.0,
                            Carboidratos = 0.0,
                            Fibras = 0.0,
                            Gorduras = 10.6,
                            NomeAlimento = "Bife grelhado",
                            Proteinas = 26.600000000000001,
                            Sodio = 60.0
                        },
                        new
                        {
                            IdAlimento = 41,
                            Calorias = 132.0,
                            Carboidratos = 0.0,
                            Fibras = 0.0,
                            Gorduras = 0.69999999999999996,
                            NomeAlimento = "Atum em lata",
                            Proteinas = 23.5,
                            Sodio = 360.0
                        },
                        new
                        {
                            IdAlimento = 42,
                            Calorias = 86.0,
                            Carboidratos = 20.100000000000001,
                            Fibras = 3.0,
                            Gorduras = 0.10000000000000001,
                            NomeAlimento = "Batata doce cozida",
                            Proteinas = 1.6000000000000001,
                            Sodio = 4.0
                        },
                        new
                        {
                            IdAlimento = 43,
                            Calorias = 111.0,
                            Carboidratos = 23.199999999999999,
                            Fibras = 1.8,
                            Gorduras = 1.3999999999999999,
                            NomeAlimento = "Arroz integral cozido",
                            Proteinas = 2.6000000000000001,
                            Sodio = 5.0
                        },
                        new
                        {
                            IdAlimento = 44,
                            Calorias = 120.0,
                            Carboidratos = 21.300000000000001,
                            Fibras = 2.7999999999999998,
                            Gorduras = 3.6000000000000001,
                            NomeAlimento = "Quinoa cozida",
                            Proteinas = 4.0999999999999996,
                            Sodio = 7.0
                        },
                        new
                        {
                            IdAlimento = 45,
                            Calorias = 389.0,
                            Carboidratos = 66.299999999999997,
                            Fibras = 10.6,
                            Gorduras = 6.9000000000000004,
                            NomeAlimento = "Aveia",
                            Proteinas = 11.9,
                            Sodio = 2.0
                        },
                        new
                        {
                            IdAlimento = 46,
                            Calorias = 158.0,
                            Carboidratos = 31.0,
                            Fibras = 3.2999999999999998,
                            Gorduras = 1.5,
                            NomeAlimento = "Macarrão integral cozido",
                            Proteinas = 5.7999999999999998,
                            Sodio = 2.0
                        },
                        new
                        {
                            IdAlimento = 47,
                            Calorias = 98.0,
                            Carboidratos = 26.300000000000001,
                            Fibras = 0.0,
                            Gorduras = 0.29999999999999999,
                            NomeAlimento = "Tapioca",
                            Proteinas = 0.10000000000000001,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 48,
                            Calorias = 312.0,
                            Carboidratos = 35.399999999999999,
                            Fibras = 3.0,
                            Gorduras = 19.199999999999999,
                            NomeAlimento = "Batata frita",
                            Proteinas = 3.3999999999999999,
                            Sodio = 320.0
                        },
                        new
                        {
                            IdAlimento = 49,
                            Calorias = 207.0,
                            Carboidratos = 21.100000000000001,
                            Fibras = 0.0,
                            Gorduras = 6.7000000000000002,
                            NomeAlimento = "Sorvete de creme",
                            Proteinas = 2.7000000000000002,
                            Sodio = 45.0
                        },
                        new
                        {
                            IdAlimento = 50,
                            Calorias = 506.0,
                            Carboidratos = 57.700000000000003,
                            Fibras = 2.3999999999999999,
                            Gorduras = 24.600000000000001,
                            NomeAlimento = "Biscoito recheado",
                            Proteinas = 4.2000000000000002,
                            Sodio = 400.0
                        },
                        new
                        {
                            IdAlimento = 51,
                            Calorias = 453.0,
                            Carboidratos = 55.399999999999999,
                            Fibras = 6.2999999999999998,
                            Gorduras = 28.399999999999999,
                            NomeAlimento = "Pipoca de micro-ondas",
                            Proteinas = 8.0999999999999996,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 52,
                            Calorias = 535.0,
                            Carboidratos = 59.700000000000003,
                            Fibras = 7.5,
                            Gorduras = 30.899999999999999,
                            NomeAlimento = "Chocolate ao leite",
                            Proteinas = 6.9000000000000004,
                            Sodio = 16.0
                        },
                        new
                        {
                            IdAlimento = 53,
                            Calorias = 52.0,
                            Carboidratos = 13.800000000000001,
                            Fibras = 2.1000000000000001,
                            Gorduras = 0.29999999999999999,
                            NomeAlimento = "Maçã verde",
                            Proteinas = 0.29999999999999999,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 54,
                            Calorias = 69.0,
                            Carboidratos = 17.199999999999999,
                            Fibras = 0.90000000000000002,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Uva",
                            Proteinas = 0.59999999999999998,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 55,
                            Calorias = 32.0,
                            Carboidratos = 6.7000000000000002,
                            Fibras = 1.6000000000000001,
                            Gorduras = 0.40000000000000002,
                            NomeAlimento = "Morango",
                            Proteinas = 0.80000000000000004,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 56,
                            Calorias = 60.0,
                            Carboidratos = 14.800000000000001,
                            Fibras = 1.6000000000000001,
                            Gorduras = 0.29999999999999999,
                            NomeAlimento = "Manga",
                            Proteinas = 0.59999999999999998,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 57,
                            Calorias = 61.0,
                            Carboidratos = 15.199999999999999,
                            Fibras = 3.1000000000000001,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Pera",
                            Proteinas = 0.40000000000000002,
                            Sodio = 1.0
                        },
                        new
                        {
                            IdAlimento = 58,
                            Calorias = 37.0,
                            Carboidratos = 9.4000000000000004,
                            Fibras = 0.59999999999999998,
                            Gorduras = 0.20000000000000001,
                            NomeAlimento = "Melão",
                            Proteinas = 0.59999999999999998,
                            Sodio = 2.0
                        },
                        new
                        {
                            IdAlimento = 59,
                            Calorias = 61.0,
                            Carboidratos = 14.699999999999999,
                            Fibras = 2.5,
                            Gorduras = 0.59999999999999998,
                            NomeAlimento = "Kiwi",
                            Proteinas = 1.1000000000000001,
                            Sodio = 3.0
                        },
                        new
                        {
                            IdAlimento = 60,
                            Calorias = 367.0,
                            Carboidratos = 77.0,
                            Fibras = 13.0,
                            Gorduras = 0.40000000000000002,
                            NomeAlimento = "Goji berry",
                            Proteinas = 12.0,
                            Sodio = 3.0
                        },
                        new
                        {
                            IdAlimento = 61,
                            Calorias = 655.0,
                            Carboidratos = 12.9,
                            Fibras = 5.0,
                            Gorduras = 66.400000000000006,
                            NomeAlimento = "Castanha-do-pará",
                            Proteinas = 14.300000000000001,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 62,
                            Calorias = 575.0,
                            Carboidratos = 21.100000000000001,
                            Fibras = 12.5,
                            Gorduras = 49.399999999999999,
                            NomeAlimento = "Amêndoa",
                            Proteinas = 21.199999999999999,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 63,
                            Calorias = 650.0,
                            Carboidratos = 16.100000000000001,
                            Fibras = 9.6999999999999993,
                            Gorduras = 61.399999999999999,
                            NomeAlimento = "Avelã",
                            Proteinas = 14.9,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 64,
                            Calorias = 654.0,
                            Carboidratos = 13.0,
                            Fibras = 6.7000000000000002,
                            Gorduras = 65.200000000000003,
                            NomeAlimento = "Nozes",
                            Proteinas = 14.0,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 65,
                            Calorias = 562.0,
                            Carboidratos = 27.699999999999999,
                            Fibras = 10.6,
                            Gorduras = 45.399999999999999,
                            NomeAlimento = "Pistache",
                            Proteinas = 20.899999999999999,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 66,
                            Calorias = 574.0,
                            Carboidratos = 10.0,
                            Fibras = 6.0,
                            Gorduras = 45.799999999999997,
                            NomeAlimento = "Semente de abóbora",
                            Proteinas = 29.800000000000001,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 67,
                            Calorias = 582.0,
                            Carboidratos = 20.0,
                            Fibras = 8.5999999999999996,
                            Gorduras = 51.5,
                            NomeAlimento = "Semente de girassol",
                            Proteinas = 19.300000000000001,
                            Sodio = 0.0
                        },
                        new
                        {
                            IdAlimento = 68,
                            Calorias = 235.0,
                            Carboidratos = 19.399999999999999,
                            Fibras = 0.90000000000000002,
                            Gorduras = 12.800000000000001,
                            NomeAlimento = "Pão de queijo",
                            Proteinas = 3.2000000000000002,
                            Sodio = 384.0
                        });
                });

            modelBuilder.Entity("regrando.API.Models.Cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceitouTermos")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("TB_CADASTRO");
                });

            modelBuilder.Entity("regrando.API.Models.Objetivo", b =>
                {
                    b.Property<int>("IdObjetivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObjetivo"));

                    b.Property<string>("DsObjetivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("TipoObjetivo")
                        .HasColumnType("int");

                    b.HasKey("IdObjetivo");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("TB_OBJETIVO");

                    b.HasData(
                        new
                        {
                            IdObjetivo = 1,
                            DsObjetivo = "Manutenção da Saúde Geral",
                            IdUsuario = 1,
                            TipoObjetivo = 1
                        },
                        new
                        {
                            IdObjetivo = 2,
                            DsObjetivo = "Ganho de Massa Muscular",
                            IdUsuario = 2,
                            TipoObjetivo = 2
                        },
                        new
                        {
                            IdObjetivo = 3,
                            DsObjetivo = "Melhoria da Saúde Digestiva",
                            IdUsuario = 3,
                            TipoObjetivo = 3
                        },
                        new
                        {
                            IdObjetivo = 4,
                            DsObjetivo = "Perda de Peso",
                            IdUsuario = 4,
                            TipoObjetivo = 4
                        });
                });

            modelBuilder.Entity("regrando.API.Models.Receita", b =>
                {
                    b.Property<int>("IdReceita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReceita"));

                    b.Property<int>("Calorias")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("NomeReceita")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("TempoPreparoMinutos")
                        .HasColumnType("int");

                    b.HasKey("IdReceita");

                    b.ToTable("TB_RECEITA");

                    b.HasData(
                        new
                        {
                            IdReceita = 1,
                            Calorias = 200,
                            Descricao = "Delicioso bolo de cenoura com cobertura de chocolate",
                            Ingredientes = "Cenoura, óleo, ovos, açúcar, farinha de trigo, fermento em pó, chocolate",
                            ModoPreparo = "1. Bata no liquidificador as cenouras, óleo e ovos. 2. Adicione o açúcar e a farinha de trigo. 3. Por último, coloque o fermento e misture delicadamente. 4. Asse em forno médio por aproximadamente 40 minutos.",
                            NomeReceita = "Bolo de cenoura",
                            TempoPreparoMinutos = 40
                        },
                        new
                        {
                            IdReceita = 2,
                            Calorias = 150,
                            Descricao = "Salada refrescante com quinoa, tomate, pepino e temperos",
                            Ingredientes = "Quinoa, tomate, pepino, azeite, limão, sal",
                            ModoPreparo = "1. Cozinhe a quinoa conforme as instruções da embalagem. 2. Corte os tomates e pepinos em cubos. 3. Misture tudo e tempere a gosto. 4. Sirva frio.",
                            NomeReceita = "Salada de quinoa",
                            TempoPreparoMinutos = 30
                        });
                });

            modelBuilder.Entity("regrando.API.Models.Refeicoes", b =>
                {
                    b.Property<int>("IdRefeicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRefeicao"));

                    b.Property<TimeSpan?>("HrRefeicao")
                        .HasColumnType("time");

                    b.Property<int>("IdAlimento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TpRefeicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("IdRefeicao");

                    b.ToTable("TB_REFEICOES");

                    b.HasData(
                        new
                        {
                            IdRefeicao = 1,
                            HrRefeicao = new TimeSpan(0, 12, 0, 0, 0),
                            IdAlimento = 1,
                            IdUsuario = 1,
                            TpRefeicao = "Almoço"
                        },
                        new
                        {
                            IdRefeicao = 2,
                            HrRefeicao = new TimeSpan(0, 19, 0, 0, 0),
                            IdAlimento = 2,
                            IdUsuario = 2,
                            TpRefeicao = "Jantar"
                        });
                });

            modelBuilder.Entity("regrando.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("Objetivo")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("IdUsuario");

                    b.ToTable("TB_USUARIO");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Altura = 1.75,
                            Cpf = "123456789",
                            Nome = "Exemplo",
                            Objetivo = 1,
                            Peso = 70,
                            Sexo = "Masculino"
                        });
                });

            modelBuilder.Entity("regrando.API.Models.Cadastro", b =>
                {
                    b.HasOne("regrando.API.Models.Usuario", "Usuario")
                        .WithOne("Cadastro")
                        .HasForeignKey("regrando.API.Models.Cadastro", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("regrando.API.Models.Usuario", b =>
                {
                    b.Navigation("Cadastro")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
