// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using regrando.API.Data;

#nullable disable

namespace regrando.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240616161732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("regrando.API.Models.Aguas", b =>
                {
                    b.Property<int>("IdAgua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgua"));

                    b.Property<TimeSpan?>("HrAgua")
                        .HasColumnType("time");

                    b.Property<int?>("QtdAgua")
                        .HasColumnType("int");

                    b.HasKey("IdAgua");

                    b.ToTable("TB_AGUAS");

                    b.HasData(
                        new
                        {
                            IdAgua = 1,
                            HrAgua = new TimeSpan(0, 8, 0, 0, 0),
                            QtdAgua = 200
                        },
                        new
                        {
                            IdAgua = 2,
                            HrAgua = new TimeSpan(0, 12, 0, 0, 0),
                            QtdAgua = 300
                        });
                });

            modelBuilder.Entity("regrando.API.Models.Refeicoes", b =>
                {
                    b.Property<int>("IdRefeicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRefeicao"));

                    b.Property<TimeSpan?>("HrRefeicao")
                        .HasColumnType("time");

                    b.Property<int>("IdAlimento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TpRefeicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("IdRefeicao");

                    b.ToTable("TB_REFEICOES");

                    b.HasData(
                        new
                        {
                            IdRefeicao = 1,
                            HrRefeicao = new TimeSpan(0, 12, 0, 0, 0),
                            IdAlimento = 1,
                            IdUsuario = 1,
                            TpRefeicao = "Almoço"
                        },
                        new
                        {
                            IdRefeicao = 2,
                            HrRefeicao = new TimeSpan(0, 19, 0, 0, 0),
                            IdAlimento = 2,
                            IdUsuario = 1,
                            TpRefeicao = "Jantar"
                        });
                });

            modelBuilder.Entity("regrando.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("Objetivo")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("IdUsuario");

                    b.ToTable("TB_USUARIO");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Altura = 1.75,
                            Cpf = "123456789",
                            Nome = "Exemplo",
                            Objetivo = 1,
                            Peso = 70,
                            Sexo = "Masculino"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
